updated google analytics code
PecanProject/bety pull request #755
Opened 2024-07-09 18:16 UTC by dlebauer

Updates to new Google Analytics tracking code. Not required, but would be nice to deploy esp to www.betydb.org

could also limit to only checking when on betydb.org

```
if (location.hostname === 'betydb.org' || location.hostname === 'www.betydb.org') {
 <new code>
}
```

2024-07-09 19:11 UTC, robkooper requested changes

2024-07-09 19:11 UTC, robkooper commented on app/views/layouts/fullscreen.html.erb
> +    gtag('config', 'G-2PN4PE3MT2');
should this be hardcoded in the app, can we make this an option in the config?

2024-07-09 19:11 UTC, robkooper commented on public/UI_redesign/index.html
> +<script async src="https://www.googletagmanager.com/gtag/js?id=G-2PN4PE3MT2"></script>
can this be a configuration option.

2024-07-09 19:11 UTC, robkooper commented on public/UI_redesign/index.html
> +  gtag('config', 'G-2PN4PE3MT2');
final location can this be a configuration option.

2024-07-09 19:11 UTC, robkooper commented on app/views/layouts/application.html.erb
> +  <script async src="https://www.googletagmanager.com/gtag/js?id=G-2PN4PE3MT2"></script>
can this be a configuration option?

2024-07-10 03:06 UTC, dlebauer commented on app/views/layouts/fullscreen.html.erb
> +    gtag('config', 'G-2PN4PE3MT2');
As it stands this PR restores functionality that was lost when google changed its api. Moving this to a configuration file is a great idea. 

I proposed this in https://github.com/PecanProject/bety/issues/511 but it seems like a heavy lift in the absence of a rails developer (and I closed the issue earlier today after giving up on it / realizing that it is a low priority).

2024-07-13 16:40 UTC, robkooper commented
fixed it so it will not have hardcoded google analytics code.

2024-07-14 11:57 UTC, dlebauer commented
Thanks - where is / did you update the betydb.org configuration file?

2024-07-14 14:30 UTC, merged